name: Deploy Hugo Site to Host

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Sync files to FTP
        uses: SamKirsch/ftp-deploy-action@v4.3.4
        with:
          server: ${{ https://brainping.me:2222 }}
          username: ${{ braingr }}
          password: ${{ pE4stQ0I#52Os; }}
          server-dir: /public_html/
